import { useState, type ReactNode } from "react";
import { createAdminControlPlane } from "../../../../../packages/pack04/controlPlane";

const base = { actorUserId: "system-a", accountState: "ACTIVE" as const, tenantId: "tenant-a", teamIds: ["team-a"], verifiedRoleGrants: [], guardianRelations: [], consents: [], safeguardingBlocked: false, feature: "CORE" as const, operation: "admin:operate" as const };
const grants = [{ id: "system", role: "SYSTEM_ADMIN" as const, status: "VERIFIED" as const, tenantId: "tenant-a" }, { id: "verify", role: "ROLE_VERIFICATION_OPERATOR" as const, status: "VERIFIED" as const, tenantId: "tenant-a" }, { id: "moderator", role: "COMMUNITY_MODERATOR" as const, status: "VERIFIED" as const, tenantId: "tenant-a" }, { id: "safety", role: "SAFEGUARDING_OFFICER" as const, status: "VERIFIED" as const, tenantId: "tenant-a", caseIds: ["case-a"] }, { id: "privacy", role: "PRIVACY_OPERATOR" as const, status: "VERIFIED" as const, tenantId: "tenant-a" }, { id: "migration", role: "MIGRATION_OPERATOR" as const, status: "VERIFIED" as const, tenantId: "tenant-a" }];
const control = createAdminControlPlane(base, grants);
function Frame({ title, children }: { title: string; children: ReactNode }) { return <main className="shell-main"><p className="eyebrow">ADMIN / OPS · LOCAL ONLY</p><h1>{title}</h1>{children}</main>; }
export function AdminOverviewPage() { const overview = control.systemOverview("system"); const gate = control.featureGate("system", "EPTS"); return <Frame title="관리 운영 콘솔"><section className="surface-card"><h2>시스템 개요</h2><p>tenant: {overview.tenants} · audit/read model only</p><p>EPTS: {gate.enabled ? "활성" : "활성화 불가"} · production {gate.productionActivation}</p><p>System Admin은 safeguarding/privacy specialist case를 자동 열람할 수 없습니다.</p></section></Frame>; }
export function RoleVerificationAdminPage() { const [status, setStatus] = useState(""); return <Frame title="역할 검증"><section className="surface-card"><h2>검증 결정</h2><p>evidence metadata가 없는 승인과 self approval은 허용되지 않습니다.</p><button onClick={() => setStatus(control.decideVerification("verify", { targetUserId: "manager-b", evidenceRef: "local-reference-only", decision: "APPROVE" }).state)}>로컬 승인 검토</button>{status && <p role="status">{status}</p>}</section></Frame>; }
export function ModerationAdminPage() { const [status, setStatus] = useState(""); return <Frame title="커뮤니티 moderation"><section className="surface-card"><h2>신고 queue</h2><p>Community write owner는 Legacy입니다. 이 화면은 최소 정보 projection만 제공합니다.</p><button onClick={() => setStatus(control.reviewModeration("moderator", "report-local", "ACTIONED").mode)}>로컬 검토 기록</button>{status && <p role="status">{status}</p>}</section></Frame>; }
export function SafeguardingAdminPage() { return <Frame title="Safeguarding"><section className="surface-card"><h2>제한된 case reference</h2><p>case-level need-to-know · evidence body는 projection에 포함하지 않습니다.</p><p>Support, Community Moderator, System Admin은 이 private case를 열 수 없습니다.</p></section></Frame>; }
export function PrivacyAdminPage() { const [status, setStatus] = useState(""); return <Frame title="Privacy operations"><section className="surface-card"><h2>삭제 요청 workflow</h2><p>실제 데이터 삭제는 수행하지 않습니다.</p><button onClick={() => setStatus(control.advancePrivacyRequest("privacy", "request-local", "DELETE").state)}>삭제 workflow 검토</button>{status && <p role="status">{status}</p>}</section></Frame>; }
export function MigrationAdminPage() { const [status, setStatus] = useState(""); return <Frame title="Migration operations"><section className="surface-card"><h2>Migration rehearsal</h2><p>LOCAL / REHEARSAL만 표현하며 production cutover는 차단됩니다.</p><button onClick={() => setStatus(control.runMigration("migration", "plan-local", "PRODUCTION").state)}>Production 실행 요청</button>{status && <p role="status">{status}</p>}</section></Frame>; }
export function JobsMediaAdminPage() { return <Frame title="Jobs / Media"><section className="surface-card"><h2>운영 projection</h2><p>retry는 infra gate 전까지 deferred이며 production media mutation은 없습니다.</p></section></Frame>; }
export function AuditAdminPage() { return <Frame title="Audit"><section className="surface-card"><h2>안전한 audit</h2><p>actor, scope, action, decision만 표시합니다. token, secret, private message/body는 포함하지 않습니다.</p></section></Frame>; }
export function EarthusHealthAdminPage() { const health = control.earthusHealth(); return <Frame title="Earthus Health"><section className="surface-card"><h2>{health.status}</h2><p>Soft dependency · authorization, training, match, career, communication을 차단하지 않습니다.</p></section></Frame>; }
