import { authorize, type AuthorizationContext } from "../shared-security/authorization";

type CoachContext = AuthorizationContext;
type TrainingState = "DRAFT" | "READY" | "CHECK_IN" | "LIVE" | "ENDED" | "PROCESSING" | "REVIEW" | "PUBLISHED" | "ARCHIVED" | "CANCELLED" | "FAILED_PARTIAL";
type MatchState = "DRAFT" | "SCHEDULED" | "CHECK_IN" | "LIVE" | "HALFTIME" | "ENDED" | "FINALIZED" | "CANCELLED" | "POSTPONED";
const canonicalMatchEvents = new Set(["MATCH_START", "PERIOD_START", "PERIOD_END", "GOAL", "OWN_GOAL", "SUBSTITUTION", "YELLOW_CARD", "RED_CARD", "INCIDENT", "ADDED_TIME", "MATCH_END", "CORRECTION"]);

function assertAllowed(context: AuthorizationContext, teamId: string) {
  const decision = authorize({ ...context, resourceTenantId: context.tenantId, resourceTeamId: teamId });
  if (decision.decision === "DENY") throw new Error(decision.reason);
}

export function createPack01Domain() {
  let sequence = 0;
  const id = (prefix: string) => `${prefix}-${++sequence}`;
  const sessions = new Map<string, { id: string; teamId: string; objective: string; state: TrainingState; version: number; plans: Array<{ version: number; objective: string; drills: string[] }>; participation: Map<string, string>; attendance: Map<string, string> }>();
  const matches = new Map<string, { id: string; teamId: string; opponent: string; state: MatchState; version: number; roster: Set<string>; lineup: { starters: string[]; substitutes: string[]; captain: string | null }; events: Array<{ idempotencyKey: string; type: string; athleteId: string }>; referees: Set<string> }>();
  const tactics = new Map<string, { id: string; teamId: string; name: string; versions: Array<{ version: number; mode: "PLAN_TACTIC" | "ACTUAL"; paths: string[] }> }>();

  return {
    createTrainingSession(context: CoachContext, input: { teamId: string; objective: string }) { assertAllowed(context, input.teamId); const session = { id: id("training"), teamId: input.teamId, objective: input.objective, state: "DRAFT" as TrainingState, version: 1, plans: [{ version: 1, objective: input.objective, drills: [] }], participation: new Map<string, string>(), attendance: new Map<string, string>() }; sessions.set(session.id, session); return session; },
    transitionTraining(context: CoachContext, sessionId: string, next: TrainingState, expectedVersion: number) { const session = sessions.get(sessionId); if (!session) throw new Error("NOT_FOUND"); assertAllowed(context, session.teamId); if (session.version !== expectedVersion) throw new Error("VERSION_CONFLICT"); const transitions: Record<TrainingState, TrainingState[]> = { DRAFT: ["READY", "CANCELLED"], READY: ["CHECK_IN", "CANCELLED"], CHECK_IN: ["LIVE", "CANCELLED"], LIVE: ["ENDED", "FAILED_PARTIAL"], ENDED: ["PROCESSING"], PROCESSING: ["REVIEW"], REVIEW: ["PUBLISHED", "ARCHIVED"], PUBLISHED: ["ARCHIVED"], ARCHIVED: [], CANCELLED: [], FAILED_PARTIAL: ["REVIEW"] }; if (!transitions[session.state].includes(next)) throw new Error("TRAINING_TRANSITION_INVALID"); session.state = next; session.version += 1; return session; },
    updateTrainingPlan(context: CoachContext, sessionId: string, input: { objective: string; drills: string[] }, expectedVersion: number) { const session = sessions.get(sessionId); if (!session) throw new Error("NOT_FOUND"); assertAllowed(context, session.teamId); if (session.version !== expectedVersion) throw new Error("VERSION_CONFLICT"); session.version += 1; const revision = { version: session.version, ...input }; session.plans.push(revision); return revision; },
    setParticipation(context: AuthorizationContext, sessionId: string, athleteId: string, response: "GOING" | "NOT_GOING" | "LATE") { const session = sessions.get(sessionId); if (!session) throw new Error("NOT_FOUND"); if (context.actorUserId !== athleteId) throw new Error("RESOURCE_SCOPE_MISMATCH"); session.participation.set(athleteId, response); return { response }; },
    setAttendance(context: CoachContext, sessionId: string, athleteId: string, state: "PRESENT" | "ABSENT" | "LATE") { const session = sessions.get(sessionId); if (!session) throw new Error("NOT_FOUND"); assertAllowed(context, session.teamId); session.attendance.set(athleteId, state); return { state }; },
    createMatch(context: CoachContext, input: { teamId: string; opponent: string }) { assertAllowed(context, input.teamId); const match = { id: id("match"), teamId: input.teamId, opponent: input.opponent, state: "DRAFT" as MatchState, version: 1, roster: new Set<string>(), lineup: { starters: [], substitutes: [], captain: null as string | null }, events: [] as Array<{ idempotencyKey: string; type: string; athleteId: string }>, referees: new Set<string>() }; matches.set(match.id, match); return match; },
    transitionMatch(context: CoachContext, matchId: string, next: MatchState, expectedVersion: number) { const match = matches.get(matchId); if (!match) throw new Error("NOT_FOUND"); assertAllowed(context, match.teamId); if (match.version !== expectedVersion) throw new Error("VERSION_CONFLICT"); const transitions: Record<MatchState, MatchState[]> = { DRAFT: ["SCHEDULED", "CANCELLED"], SCHEDULED: ["CHECK_IN", "POSTPONED", "CANCELLED"], CHECK_IN: ["LIVE", "CANCELLED"], LIVE: ["HALFTIME", "ENDED"], HALFTIME: ["LIVE", "ENDED"], ENDED: ["FINALIZED"], FINALIZED: [], CANCELLED: [], POSTPONED: ["SCHEDULED", "CANCELLED"] }; if (!transitions[match.state].includes(next)) throw new Error("MATCH_TRANSITION_INVALID"); match.state = next; match.version += 1; return match; },
    getMatch(matchId: string) { const match = matches.get(matchId); if (!match) throw new Error("NOT_FOUND"); return match; },
    updateRoster(context: CoachContext, matchId: string, players: string[]) { const match = matches.get(matchId); if (!match) throw new Error("NOT_FOUND"); assertAllowed(context, match.teamId); players.forEach((player) => match.roster.add(player)); return [...match.roster]; },
    updateLineup(context: CoachContext, matchId: string, input: { starters: string[]; substitutes: string[]; captain: string | null }) { const match = matches.get(matchId); if (!match) throw new Error("NOT_FOUND"); assertAllowed(context, match.teamId); if (input.captain && !input.starters.includes(input.captain)) throw new Error("CAPTAIN_MUST_START"); if (![...input.starters, ...input.substitutes].every((player) => match.roster.has(player))) throw new Error("ROSTER_SCOPE_MISMATCH"); match.lineup = { ...input }; return match.lineup; },
    recordMatchEvent(context: CoachContext, matchId: string, input: { idempotencyKey: string; type: string; athleteId: string }) { const match = matches.get(matchId); if (!match) throw new Error("NOT_FOUND"); assertAllowed(context, match.teamId); if (!canonicalMatchEvents.has(input.type)) throw new Error("MATCH_EVENT_TYPE_INVALID"); if (!match.events.some((event) => event.idempotencyKey === input.idempotencyKey)) match.events.push(input); return match; },
    assignReferee(context: CoachContext, matchId: string, refereeId: string) { const match = matches.get(matchId); if (!match) throw new Error("NOT_FOUND"); assertAllowed(context, match.teamId); match.referees.add(refereeId); },
    createMatchReport(context: AuthorizationContext, matchId: string, _body: string) { const match = matches.get(matchId); if (!match) throw new Error("NOT_FOUND"); if (!context.verifiedRoleGrants.some((grant) => grant.role === "REFEREE" && grant.status === "VERIFIED" && grant.tenantId === context.tenantId) || !match.referees.has(context.actorUserId ?? "")) throw new Error("REFEREE_ASSIGNMENT_REQUIRED"); return { state: "DRAFT" as const }; },
    createTactic(context: CoachContext, input: { teamId: string; name: string }) { assertAllowed(context, input.teamId); const tactic = { id: id("tactic"), teamId: input.teamId, name: input.name, versions: [] as Array<{ version: number; mode: "PLAN_TACTIC" | "ACTUAL"; paths: string[] }> }; tactics.set(tactic.id, tactic); return tactic; },
    createTacticVersion(context: CoachContext, tacticId: string, input: { mode: "PLAN_TACTIC" | "ACTUAL"; paths: string[] }) { const tactic = tactics.get(tacticId); if (!tactic) throw new Error("NOT_FOUND"); assertAllowed(context, tactic.teamId); const version = { version: tactic.versions.length + 1, ...input }; tactic.versions.push(version); return version; },
    getTacticalPlayback(context: CoachContext, tacticId: string) { const tactic = tactics.get(tacticId); if (!tactic) throw new Error("NOT_FOUND"); assertAllowed(context, tactic.teamId); return { mode: "STATIC" as const, editable: false, version: tactic.versions.at(-1) ?? null }; },
    createOfflineQueue() { const pending = new Map<string, { id: string; idempotencyKey: string; action: string; failOnce?: boolean; conflict?: boolean; attempts?: number }>(); const applied = new Set<string>(); return { enqueue(command: { id: string; idempotencyKey: string; action: string; failOnce?: boolean; conflict?: boolean }) { pending.set(command.id, { ...command, attempts: 0 }); }, reconnect() { const newlyApplied: string[] = []; const conflicts: string[] = []; const retryable: string[] = []; for (const [key, command] of pending) { command.attempts = (command.attempts ?? 0) + 1; if (command.conflict) { conflicts.push(command.id); pending.delete(key); continue; } if (command.failOnce && command.attempts === 1) { retryable.push(command.id); continue; } if (!applied.has(command.idempotencyKey)) { applied.add(command.idempotencyKey); newlyApplied.push(command.id); } pending.delete(key); } return { applied: newlyApplied, conflicts, retryable }; } }; }
  };
}
