/* eslint-disable no-undef */
import type { CoreVisualMode } from "../api/coreProductContracts";
type V=readonly[number,number,number]; type C=readonly[number,number,number];
interface M{p:number[];n:number[];c:number[];i:number[]}
export interface StadiumWebglRenderer{readonly triangleCount:number;resize(w:number,h:number,dpr:number):void;render(orbit:number,zoom:number):void;destroy():void}
const K={grass1:[.025,.23,.055]as C,grass2:[.018,.17,.04]as C,white:[.92,.94,.95]as C,seat:[.018,.045,.095]as C,seatB:[.02,.09,.22]as C,con:[.16,.17,.18]as C,dark:[.012,.016,.022]as C,steel:[.25,.28,.31]as C,roof:[.11,.13,.16]as C,blue:[.02,.18,.72]as C,warm:[1,.78,.48]as C,crowd:[.24,.28,.33]as C};
const m=():M=>({p:[],n:[],c:[],i:[]}); const sub=(a:V,b:V):V=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]]; const cross=(a:V,b:V):V=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]; const norm=(a:V):V=>{const l=Math.hypot(...a)||1;return[a[0]/l,a[1]/l,a[2]/l]};
function face(x:M,a:V,b:V,c:V,d:V,col:C){const n=norm(cross(sub(b,a),sub(c,a))),s=x.p.length/3;for(const q of[a,b,c,d]){x.p.push(...q);x.n.push(...n);x.c.push(...col)}x.i.push(s,s+1,s+2,s,s+2,s+3)}
function box(x:M,[px,py,pz]:V,[sx,sy,sz]:V,col:C){const a=px-sx/2,b=px+sx/2,c=py-sy/2,d=py+sy/2,e=pz-sz/2,f=pz+sz/2;face(x,[a,c,f],[b,c,f],[b,d,f],[a,d,f],col);face(x,[b,c,e],[a,c,e],[a,d,e],[b,d,e],col);face(x,[a,c,e],[a,c,f],[a,d,f],[a,d,e],col);face(x,[b,c,f],[b,c,e],[b,d,e],[b,d,f],col);face(x,[a,d,f],[b,d,f],[b,d,e],[a,d,e],col);face(x,[a,c,e],[b,c,e],[b,c,f],[a,c,f],col)}
function plane(x:M,x0:number,x1:number,z0:number,z1:number,y:number,col:C){face(x,[x0,y,z0],[x0,y,z1],[x1,y,z1],[x1,y,z0],col)}
function ring(x:M,ix:number,iz:number,ox:number,oz:number,y0:number,y1:number,seg:number,col:C,frontCut=.86){for(let j=0;j<seg;j++){const a=j/seg*Math.PI*2,b=(j+1)/seg*Math.PI*2,mid=(a+b)/2;if(Math.sin(mid)>frontCut)continue;face(x,[Math.cos(a)*ix,y0,Math.sin(a)*iz],[Math.cos(b)*ix,y0,Math.sin(b)*iz],[Math.cos(b)*ox,y1,Math.sin(b)*oz],[Math.cos(a)*ox,y1,Math.sin(a)*oz],col)}}
function circle(x:M,r:number,w:number,y:number,seg:number,col:C){for(let j=0;j<seg;j++){const a=j/seg*Math.PI*2,b=(j+1)/seg*Math.PI*2;face(x,[Math.cos(a)*(r-w/2),y,Math.sin(a)*(r-w/2)],[Math.cos(b)*(r-w/2),y,Math.sin(b)*(r-w/2)],[Math.cos(b)*(r+w/2),y,Math.sin(b)*(r+w/2)],[Math.cos(a)*(r+w/2),y,Math.sin(a)*(r+w/2)],col)}}
function pitch(x:M,seg:number){plane(x,-58,58,-39,39,-.12,K.dark);for(let j=0;j<14;j++){const a=-52.5+j*7.5;plane(x,a,a+7.51,-34,34,.04,j%2?K.grass1:K.grass2)}for(const [p,s] of [[[0,.12,-34],[105,.06,.16]],[[0,.12,34],[105,.06,.16]],[[-52.5,.12,0],[.16,.06,68]],[[52.5,.12,0],[.16,.06,68]],[[0,.12,0],[.16,.06,68]]] as const)box(x,p,s,K.white);circle(x,9.15,.16,.14,64,K.white);for(const side of[-1,1] as const){const gx=side*52.5,px=gx-side*16.5;box(x,[px,.12,0],[.16,.06,40.32],K.white);box(x,[(gx+px)/2,.12,-20.16],[16.5,.06,.16],K.white);box(x,[(gx+px)/2,.12,20.16],[16.5,.06,.16],K.white);const post=gx+side*.2;box(x,[post,1.22,-3.66],[.12,2.44,.12],K.white);box(x,[post,1.22,3.66],[.12,2.44,.12],K.white);box(x,[post,2.44,0],[.12,.12,7.44],K.white)}}
function tier(x:M,baseX:number,baseZ:number,rows:number,step:number,rise:number,y:number,seats:number,seg:number,col:C){for(let r=0;r<rows;r++){const ix=baseX+r*step,iz=baseZ+r*step*.72,ox=ix+step*.92,oz=iz+step*.66,yy=y+r*rise;ring(x,ix,iz,ox,oz,yy,yy+.08,seg,r%3===0?K.seatB:col,.90);for(let s=0;s<seats;s++){if((s*17+r*31)%23<4)continue;const a=(s+.5)/seats*Math.PI*2;if(Math.sin(a)>.88)continue;const h=(s*29+r*41)%100,cc=h>88?K.crowd:h>65?K.seatB:col,rx=ix+step*.52,rz=iz+step*.38;box(x,[Math.cos(a)*rx,yy+.28,Math.sin(a)*rz],[.13,.32,.13],cc)}}}
function architecture(x:M,seg:number){tier(x,60,42,12,1.18,.65,.7,112,seg,K.seat);ring(x,75,53.2,77,54.7,8.7,9.15,seg,K.blue,.90);tier(x,78.5,56,12,1.08,.72,10.2,124,seg,K.seatB);ring(x,91.5,65,93.5,66.5,18.5,18.95,seg,K.blue,.90);tier(x,95,68.5,11,1.06,.74,20.2,132,seg,K.seat);for(let a=0;a<36;a++){const t=a/36*Math.PI*2;if(Math.sin(t)>.88)continue;ring(x,61,43,107,77,.4,30.8,1,K.con,.90)}ring(x,93,66,114,83,35.5,40.2,seg,K.roof,.78);for(let j=0;j<40;j++){const a=j/40*Math.PI*2;if(Math.sin(a)>.76)continue;box(x,[Math.cos(a)*104,38.2,Math.sin(a)*75],[.30,6.8,.30],K.steel)}box(x,[0,28,-77],[30,10,1],K.dark);box(x,[0,28,-76.4],[26,6.4,.08],[.01,.03,.08]);for(const z of[-38.5,38.5]){box(x,[0,.65,z],[20,1.1,2],K.dark);for(let q=-8;q<=8;q+=2)box(x,[q,.45,z+(z>0?-1:1)*.4],[1,.35,.7],K.seatB)}for(const sx of[-100,100])for(const sz of[-70,70]){box(x,[sx,21,sz],[.55,42,.55],K.steel);box(x,[sx+(sx>0?-3:3),42,sz],[12,3,1],K.dark);for(let q=0;q<8;q++)box(x,[sx+(sx>0?-1:1)*(1+q*1.25),43.1,sz],[.8,.55,.2],K.warm)}}
function build(mode:Exclude<CoreVisualMode,"STATIC">){const x=m(),seg=mode==="FULL"?150:mode==="FAST"?112:80;pitch(x,seg);architecture(x,seg);return x}
function persp(f:number,a:number,n:number,far:number){const q=1/Math.tan(f/2),nf=1/(n-far);return new Float32Array([q/a,0,0,0,0,q,0,0,0,0,(far+n)*nf,-1,0,0,2*far*n*nf,0])} const dot=(a:V,b:V)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
function look(e:V,t:V,u:V){const z=norm(sub(e,t)),xx=norm(cross(u,z)),y=cross(z,xx);return new Float32Array([xx[0],y[0],z[0],0,xx[1],y[1],z[1],0,xx[2],y[2],z[2],0,-dot(xx,e),-dot(y,e),-dot(z,e),1])}
function mul(a:Float32Array,b:Float32Array){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function sh(gl:WebGLRenderingContext,t:number,s:string){const q=gl.createShader(t);if(!q)throw Error("shader");gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q)||"shader");return q}
function prog(gl:WebGLRenderingContext){const vs=sh(gl,gl.VERTEX_SHADER,`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec3 aColor;uniform mat4 uMvp;varying vec3 p,n,c;void main(){p=aPosition;n=normalize(aNormal);c=aColor;gl_Position=uMvp*vec4(aPosition,1.);}`),fs=sh(gl,gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 p,n,c;uniform vec3 uCamera;vec3 L(vec3 lp,float power){vec3 d=lp-p;float dist=max(length(d),1.);vec3 l=normalize(d),v=normalize(uCamera-p),h=normalize(l+v);float diff=max(dot(n,l),0.);float spec=pow(max(dot(n,h),0.),32.)*.11;float att=1./(1.+.00045*dist*dist);return vec3(1.,.95,.84)*(diff+spec)*att*power;}void main(){float pitch=(1.-step(53.,abs(p.x)))*(1.-step(35.,abs(p.z)))*(1.-step(.6,p.y));vec3 base=c*(1.+pitch*.03*(sin(p.x*3.)+sin(p.z*5.)));float up=max(n.y,0.);vec3 col=base*(.065+.12*up);col+=base*L(vec3(-100.,43.,-70.),3.5);col+=base*L(vec3(100.,43.,-70.),3.5);col+=base*L(vec3(-100.,43.,70.),3.1);col+=base*L(vec3(100.,43.,70.),3.1);col+=base*vec3(.18,.20,.22)*pitch;float em=smoothstep(.70,.98,max(max(base.r,base.g),base.b));col+=base*em*.55;float fog=smoothstep(210.,410.,length(uCamera-p));col=mix(col,vec3(.01,.015,.022),fog*.22);col=col/(col+vec3(.78));col=pow(col,vec3(.88));gl_FragColor=vec4(col,1.);}`),p=gl.createProgram();if(!p)throw Error("program");gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)||"link");return p}
function buf(gl:WebGLRenderingContext,d:number[]){const b=gl.createBuffer();if(!b)throw Error("buffer");gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(d),gl.STATIC_DRAW);return b}
export function createStadiumWebglRenderer(canvas:HTMLCanvasElement,mode:Exclude<CoreVisualMode,"STATIC">):StadiumWebglRenderer|null{if(typeof window.WebGLRenderingContext==="undefined")return null;const g=canvas.getContext("webgl",{alpha:true,antialias:true,depth:true,premultipliedAlpha:false}) as WebGLRenderingContext|null;if(!g)return null;const gl=g,x=build(mode),pr=prog(gl),pb=buf(gl,x.p),nb=buf(gl,x.n),cb=buf(gl,x.c),ib=gl.createBuffer();if(!ib)throw Error("index");gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);const mx=x.i.reduce((a,b)=>Math.max(a,b),0),u32=mx>65535;if(u32&&!gl.getExtension("OES_element_index_uint"))throw Error("uint");gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,u32?new Uint32Array(x.i):new Uint16Array(x.i),gl.STATIC_DRAW);const pa=gl.getAttribLocation(pr,"aPosition"),na=gl.getAttribLocation(pr,"aNormal"),ca=gl.getAttribLocation(pr,"aColor"),um=gl.getUniformLocation(pr,"uMvp"),uc=gl.getUniformLocation(pr,"uCamera");if(pa<0||na<0||ca<0||!um||!uc)throw Error("locations");gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.disable(gl.CULL_FACE);let W=1,H=1;const bind=(b:WebGLBuffer,l:number)=>{gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(l);gl.vertexAttribPointer(l,3,gl.FLOAT,false,0,0)};function resize(w:number,h:number,dpr:number){W=Math.max(1,Math.round(w*Math.min(dpr,2)));H=Math.max(1,Math.round(h*Math.min(dpr,2)));canvas.width=W;canvas.height=H;gl.viewport(0,0,W,H)}function render(o:number,z0:number){const a=W/H,portrait=a<1,z=Math.min(1.15,Math.max(.92,z0)),rad=(o+8)*Math.PI/180,r=(portrait?195:155)/z,h=(portrait?66:48)/z,e:V=[Math.sin(rad)*r,h,Math.cos(rad)*r],v=look(e,[0,10,0],[0,1,0]),pp=persp((portrait?56:49)*Math.PI/180,a,.6,480),mvp=mul(pp,v);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(pr);bind(pb,pa);bind(nb,na);bind(cb,ca);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.uniformMatrix4fv(um,false,mvp);gl.uniform3f(uc,e[0],e[1],e[2]);gl.drawElements(gl.TRIANGLES,x.i.length,u32?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,0)}function destroy(){for(const b of[pb,nb,cb,ib])gl.deleteBuffer(b);gl.deleteProgram(pr)}return{triangleCount:x.i.length/3,resize,render,destroy}}
